name: build


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk//fdroid/debug/calendar-fdroid-debug.apk
