name: Update lunar.ics

on:
  schedule:
    - cron: '0 0 1 1,11 *'  # 每年1月和11月的1号 00:00 UTC 运行（约每10个月）
    
  workflow_dispatch:

jobs:
  update-lunar-ics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to update lunar.ics
      run: |
        python lunar.py

    - name: Commit and push changes to lunar.ics
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add lunar_calendar
        git commit -m "Update lunar_calendar.ics with new data"
        git push origin master
